# Generated by Django 6.0.1 on 2026-01-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='reusable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Jarayonda'), ('submitted', 'Topshirilgan')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='mockexam',
            name='duration',
            field=models.IntegerField(default=150, help_text='Davomiyligi (daqiqalarda)'),
        ),
    ]
