# Generated by Django 6.0.1 on 2026-01-31 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_add_reusable_to_invitecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='exams.student')),
                ('elo', models.IntegerField(default=1200)),
                ('exams_taken', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-elo'],
            },
        ),
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('elo_before', models.IntegerField()),
                ('elo_after', models.IntegerField()),
                ('elo_delta', models.IntegerField()),
                ('score_percent', models.FloatField()),
                ('exam_avg_percent', models.FloatField()),
                ('k_factor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elo_snapshot', to='exams.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to='exams.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='exams_elohi_student_5c55f1_idx')],
            },
        ),
    ]
