# Generated by Django 6.0.1 on 2026-01-31 15:37

from django.db import migrations


def create_ratings(apps, schema_editor):
    Student = apps.get_model('exams', 'Student')
    StudentRating = apps.get_model('exams', 'StudentRating')
    for student in Student.objects.all():
        StudentRating.objects.get_or_create(
            student=student,
            defaults={'elo': 1200, 'exams_taken': 0},
        )


def remove_ratings(apps, schema_editor):
    StudentRating = apps.get_model('exams', 'StudentRating')
    StudentRating.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_studentrating_elohistory'),
    ]

    operations = [
        migrations.RunPython(create_ratings, remove_ratings),
    ]
