# Generated by Django 6.0.1 on 2026-01-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_populate_student_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDifficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('sub_part', models.CharField(blank=True, max_length=1, null=True)),
                ('beta', models.FloatField(help_text='Rasch difficulty parameter')),
                ('infit', models.FloatField(blank=True, help_text='Infit MNSQ', null=True)),
                ('outfit', models.FloatField(blank=True, help_text='Outfit MNSQ', null=True)),
                ('calibrated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_difficulties', to='exams.mockexam')),
            ],
            options={
                'unique_together': {('exam', 'question_number', 'sub_part')},
            },
        ),
    ]
