# Generated by Django 6.0.1 on 2026-02-01 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_itemdifficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Savol matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/')),
                ('topic', models.CharField(choices=[('algebra', 'Algebra'), ('geometry', 'Geometriya'), ('probability', 'Ehtimollik'), ('calculus', 'Analiz'), ('trigonometry', 'Trigonometriya'), ('number_theory', 'Sonlar nazariyasi')], max_length=50)),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('answer_type', models.CharField(choices=[('multiple_choice', "Ko'p tanlov"), ('free_response', 'Erkin javob')], default='multiple_choice', max_length=20)),
                ('choices', models.JSONField(blank=True, help_text="Variantlar ro'yxati, masalan: ['A', 'B', 'C', 'D']", null=True)),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mockexam',
            name='is_scheduled',
            field=models.BooleanField(default=False, help_text='Rejalashtirilgan imtihon'),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, help_text='Rejalashtirilgan tugash vaqti', null=True),
        ),
        migrations.AddField(
            model_name='mockexam',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='Rejalashtirilgan boshlanish vaqti', null=True),
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('light', 'Yengil (30 daq)'), ('medium', "O'rta (60 daq)")], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='Daqiqalarda')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('submitted', 'Topshirilgan')], default='in_progress', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='exams.student')),
                ('questions', models.ManyToManyField(related_name='practice_sessions', to='exams.question')),
            ],
        ),
    ]
