# Generated by Django 6.0.1 on 2026-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_question_mockexam_is_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
