# Generated by Django 6.0.1 on 2026-02-16 06:04

import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_seed_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Jarayonda'), ('submitted', 'Topshirilgan')], db_index=True, default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='mockexam',
            name='pdf_file',
            field=models.FileField(upload_to=exams.models.exam_pdf_path),
        ),
    ]
