# Generated by Django 6.0.1 on 2026-02-20 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_cleanup_mockexam_student_remove_invitecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('streak', 'Streak'), ('milestone', 'Milestone'), ('improvement', 'Improvement')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('threshold', models.FloatField(help_text='Numeric threshold for earning')),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentStreak',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='streak', serialize=False, to='exams.student')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_exam_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='elohistory',
            name='rasch_after',
            field=models.FloatField(default=50.0, help_text='Rasch scaled score after this exam'),
        ),
        migrations.AddField(
            model_name='elohistory',
            name='rasch_before',
            field=models.FloatField(default=50.0, help_text='Rasch scaled score before this exam'),
        ),
        migrations.AddField(
            model_name='studentrating',
            name='rasch_ability',
            field=models.FloatField(default=0.0, help_text='Current Rasch theta (logits)'),
        ),
        migrations.AddField(
            model_name='studentrating',
            name='rasch_scaled',
            field=models.FloatField(default=50.0, help_text='Rasch score on 0-100 scale'),
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.achievement')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='exams.student')),
            ],
            options={
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
