# Generated by Django 6.0.1 on 2026-02-20 16:36

import uuid
from django.db import migrations


def seed_achievements(apps, schema_editor):
    Achievement = apps.get_model('exams', 'Achievement')

    achievements = [
        # Milestones (Rasch score thresholds)
        {
            'type': 'milestone',
            'name': 'Novice',
            'description': 'Reach a Rasch score of 25',
            'threshold': 25,
            'icon': 'seedling',
        },
        {
            'type': 'milestone',
            'name': 'Intermediate',
            'description': 'Reach a Rasch score of 50',
            'threshold': 50,
            'icon': 'star',
        },
        {
            'type': 'milestone',
            'name': 'Advanced',
            'description': 'Reach a Rasch score of 60',
            'threshold': 60,
            'icon': 'medal',
        },
        {
            'type': 'milestone',
            'name': 'Proficient',
            'description': 'Reach a Rasch score of 70',
            'threshold': 70,
            'icon': 'award',
        },
        {
            'type': 'milestone',
            'name': 'Expert',
            'description': 'Reach a Rasch score of 80',
            'threshold': 80,
            'icon': 'crown',
        },
        {
            'type': 'milestone',
            'name': 'Master',
            'description': 'Reach a Rasch score of 90',
            'threshold': 90,
            'icon': 'gem',
        },
        {
            'type': 'milestone',
            'name': 'Grandmaster',
            'description': 'Reach a Rasch score of 95',
            'threshold': 95,
            'icon': 'diamond',
        },
        # Streaks
        {
            'type': 'streak',
            'name': '3-Exam Streak',
            'description': 'Complete 3 exams in a row',
            'threshold': 3,
            'icon': 'fire',
        },
        {
            'type': 'streak',
            'name': '5-Exam Streak',
            'description': 'Complete 5 exams in a row',
            'threshold': 5,
            'icon': 'fire',
        },
        {
            'type': 'streak',
            'name': '10-Exam Streak',
            'description': 'Complete 10 exams in a row',
            'threshold': 10,
            'icon': 'fire',
        },
        # Improvement
        {
            'type': 'improvement',
            'name': 'First Exam',
            'description': 'Complete your first exam',
            'threshold': 1,
            'icon': 'rocket',
        },
        {
            'type': 'improvement',
            'name': '5 Exams',
            'description': 'Complete 5 exams',
            'threshold': 5,
            'icon': 'trophy',
        },
        {
            'type': 'improvement',
            'name': '10 Exams',
            'description': 'Complete 10 exams',
            'threshold': 10,
            'icon': 'trophy',
        },
        {
            'type': 'improvement',
            'name': 'Rising Star',
            'description': 'Improve your score by 10%',
            'threshold': 10,
            'icon': 'trending-up',
        },
        {
            'type': 'improvement',
            'name': 'Big Leap',
            'description': 'Improve your score by 20%',
            'threshold': 20,
            'icon': 'trending-up',
        },
    ]

    for data in achievements:
        Achievement.objects.get_or_create(
            name=data['name'],
            defaults={
                'id': uuid.uuid4(),
                'type': data['type'],
                'description': data['description'],
                'threshold': data['threshold'],
                'icon': data['icon'],
            },
        )


def reverse_seed(apps, schema_editor):
    Achievement = apps.get_model('exams', 'Achievement')
    names = [
        'Novice', 'Intermediate', 'Advanced', 'Proficient', 'Expert',
        'Master', 'Grandmaster', '3-Exam Streak', '5-Exam Streak',
        '10-Exam Streak', 'First Exam', '5 Exams', '10 Exams',
        'Rising Star', 'Big Leap',
    ]
    Achievement.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_achievement_studentstreak_elohistory_rasch_after_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_achievements, reverse_seed),
    ]
