# Generated by Django 6.0.1 on 2026-02-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_add_query_optimization_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examsession',
            name='idx_session_exam_status',
        ),
        migrations.RemoveIndex(
            model_name='mockexam',
            name='idx_exam_schedule',
        ),
        migrations.RemoveIndex(
            model_name='studentanswer',
            name='idx_answer_session_question',
        ),
    ]
