# Generated by Django 6.0.1 on 2026-02-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_remove_examsession_idx_session_exam_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrating',
            name='rasch_scaled',
            field=models.FloatField(default=37.5, help_text='Rasch score on 0-75 scale (Milliy Sertifikat)'),
        ),
    ]
