# Generated by Django 6.0.1 on 2026-02-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_update_rasch_scaled_default_75'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elohistory',
            name='rasch_after',
            field=models.FloatField(default=37.5, help_text='Rasch score (0-75) after this exam'),
        ),
        migrations.AlterField(
            model_name='elohistory',
            name='rasch_before',
            field=models.FloatField(default=37.5, help_text='Rasch score (0-75) before this exam'),
        ),
    ]
